"""add updated_at and created_at fields on media table

Revision ID: 224c1e362db2
Revises: 29a1ffdf6784
Create Date: 2026-06-23 01:31:52.773474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224c1e362db2'
down_revision: Union[str, Sequence[str], None] = '29a1ffdf6784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'updated_at')
    # ### end Alembic commands ###
