"""add provider and uploaded_by fields on media table

Revision ID: 29a1ffdf6784
Revises: 4b46e6d0d673
Create Date: 2026-06-23 01:27:55.288038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a1ffdf6784'
down_revision: Union[str, Sequence[str], None] = '4b46e6d0d673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('media', sa.Column('uploaded_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'uploaded_by')
    op.drop_column('media', 'provider')
    # ### end Alembic commands ###
