"""Primary key of UUID problem fixed

Revision ID: 5053000a6094
Revises: 5e7e35b661d7
Create Date: 2026-08-25 22:17:57.924203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5053000a6094'
down_revision: Union[str, Sequence[str], None] = '5e7e35b661d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.alter_column('media', 'id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'image_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'image_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.create_index(op.f('ix_subcategories_category_id'), 'subcategories', ['category_id'], unique=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.alter_column('media', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    # ### end Alembic commands ###
